In [1]:
from asyncio.windows_events import NULL

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'D:\Projects\Sarkari-Sahayak\data\updated_data.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   scheme_name     3400 non-null   str
 1   slug            3400 non-null   str
 2   details         3400 non-null   str
 3   benefits        3400 non-null   str
 4   eligibility     3400 non-null   str
 5   application     3398 non-null   str
 6   documents       3389 non-null   str
 7   level           3400 non-null   str
 8   schemeCategory  3400 non-null   str
 9   Unnamed: 9      0 non-null      float64
 10  tags            3371 non-null   str
dtypes: float64(1), str(10)
memory usage: 12.5 MB

In [6]:
df = df.dropna(subset=["application", "documents"])

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 3387 entries, 0 to 3399
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   scheme_name     3387 non-null   str
 1   slug            3387 non-null   str
 2   details         3387 non-null   str
 3   benefits        3387 non-null   str
 4   eligibility     3387 non-null   str
 5   application     3387 non-null   str
 6   documents       3387 non-null   str
 7   level           3387 non-null   str
 8   schemeCategory  3387 non-null   str
 9   Unnamed: 9      0 non-null      float64
 10  tags            3359 non-null   str
dtypes: float64(1), str(10)
memory usage: 12.4 MB

In [8]:
df.head(5)

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,Unnamed: 9,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...",NaN,"Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,NaN,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,NaN,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,NaN,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,NaN,"Social Welfare, Financial Assistance, Deceased..."

In [10]:
df = df.drop(columns=['Unnamed: 9'])

In [11]:
df

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."
...,...,...,...,...,...,...,...,...,...,...
3395,“Ishan Uday” Special Scholarship Scheme For No...,iu-sss-ner,A scholarship scheme by the Ministry of Educat...,"1) UGC will award 10,000 (ten thousand) fresh...",The applicant must be a domicile of NER. The p...,New Registration : Step 1: Visit the Registrat...,Domicile certificate to be issued by the compe...,Central,Education & Learning,"Scholarship, Financial Assistance"
3396,“Medical Camps (Allopathy and Indian systems o...,mcacism-giapsca,The sub-scheme “Medical Camps (Allopathy and I...,Free Health Checkup and Free Medicines. Awaren...,The applicant should be 60 years or above in a...,Step 1: The interested applicant should visit ...,Aadhaar Card. Birth Certificate / Age Proof. R...,State,Health & Wellness,"Medicine, Health, Checkup, Senior Citizen, Doctor"
3397,“RAKSHAK PURASKARS’’ Award,rpa,The Directorate of Women and Child Development...,The recipients of the awarded are given a scro...,The applicant should have shown exceptional co...,Step 1: In the prescribed format of the applic...,Passport Size Photograph (Duly Attested by a G...,State,"Social welfare & Empowerment, Public Safety,La...","Award, Crime, Women, Girl, Violence, Harrassment"
3398,"“Training in Coir” Component of the ""Developme...",ticcotdocs,The scheme “Training in Coir” Component of the...,"Stipend of ₹1,500 per month per trainee during...",The applicant should be a native of Puducherry...,Step 1: The interested applicant should take p...,Residential Certificate (for verifying native ...,State,Skills & Employment,"Skill, Training, Coir, Rural, Poor, Employment"
3399,₹ 5 Lakh Insurance Cover To Farmers,farmer-insurance,"Launched on 15 August 2018, the scheme ""₹5 Lak...",Financial Security: Provides ₹5 lakh insurance...,The applicant should be a resident farmer of T...,Step 1: The farmers do not need to apply for t...,Since the ₹5 Lakh Insurance Cover for Farmers ...,State,"Agriculture,Rural & Environment, Banking,Finan...","LIC, Insurance Coverage, Financial, Security"

In [12]:
df.to_csv('compact_schemes.csv')